# Generated by Django 2.2.2 on 2021-03-05 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_en', models.CharField(blank=True, max_length=32, null=True, verbose_name='词性名称(英文)')),
                ('category_name_cn', models.CharField(blank=True, max_length=32, null=True, verbose_name='词性名称(中文)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '词性表',
                'verbose_name_plural': '词性表',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(blank=True, help_text='可应用场景', max_length=32, null=True, verbose_name='场景名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '场景表',
                'verbose_name_plural': '场景表',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_context', models.TextField(blank=True, max_length=512, null=True, verbose_name='例句内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '例句表',
                'verbose_name_plural': '例句表',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_chinese', models.CharField(blank=True, max_length=128, null=True, verbose_name='单词(中文)')),
                ('word_english', models.CharField(blank=True, max_length=128, null=True, verbose_name='单词(英文)')),
                ('phonetic_symbol', models.CharField(blank=True, max_length=32, null=True, verbose_name='音标')),
                ('phonetic_symbol_chinese', models.CharField(blank=True, max_length=32, null=True, verbose_name='注音')),
                ('word_mnemonic', models.TextField(blank=True, max_length=512, null=True, verbose_name='助记')),
                ('word_image', models.ImageField(blank=True, null=True, upload_to='word_image/', verbose_name='图片助记')),
                ('word_rank', models.IntegerField(blank=True, default=0, null=True, verbose_name='单词计分')),
                ('memory_rank', models.IntegerField(blank=True, default=0, help_text='认识+1, 模糊+0, 忘记-1', null=True, verbose_name='记忆份数')),
                ('memory_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='记忆次数')),
                ('skip_flag', models.BooleanField(default=False, verbose_name='跳过不背')),
                ('yesterday_flag', models.IntegerField(blank=True, choices=[(0, '认识'), (1, '模糊'), (2, '忘记')], default=2, null=True, verbose_name='昨日状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('category_table', models.ManyToManyField(to='app_website.Category', verbose_name='词性关联')),
                ('scenario_table', models.ManyToManyField(to='app_website.Scenario', verbose_name='关联场景')),
            ],
            options={
                'verbose_name': '单词表',
                'verbose_name_plural': '单词表',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_english', models.CharField(blank=True, max_length=128, null=True, verbose_name='单词(英文)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('word_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_website.Word', verbose_name='单词表')),
            ],
            options={
                'verbose_name': '记忆表',
                'verbose_name_plural': '记忆表',
            },
        ),
    ]
