# Generated by Django 2.2.2 on 2021-03-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en_full',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='词性名称(英文)全写'),
        ),
    ]
